server:
  port: 9091 #portnumber

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/booksdb
    password: 7777
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

#Eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka
  server:
    wait-time-in-ms-when-sync-empty: 0

# swagger
openapi:
  service:
    title: books-service doc
    version: 3.1.0
    local-url: http://localhost:9091
    dev-url: http://localhost:9091
    prod-url: http://localhost:9091

springdoc:
  api-docs:
    path: /books-service/v3/api-docs
  swagger-ui:
    path: /books-service/swagger-ui/index.html
